### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by emgiles** [Patg13/OrthoMCL_Results_Processing#1]
Hi
I am trying to use your python program to create Venn diagrams for my OrthoMCL results. I have successfully installed the program and all dependences, but an error results when I try to run the program. I think there is an issue with how I have named my species in the -c requirement. Can you please give more specific information about what you mean "Species tag list used in data."? Which data are you referring to? My species tag list is a text file that includes 8 letter species ids separated by commas. The 8 letter species ids are the same id used in the OrthoMCL groups file.

The error that occurs:
Processing Groups into ortho groups
Traceback (most recent call last):
  File "/my_working_directory/OrthoMCL/OrthoMCL_Results_Processing/./OrthoMCL_Result_Processing_Release.py", line 279, in <module>
    ortho_grps.append(ortho_group(spl[0],spl[1].replace("\n","").split(" ")))
IndexError: list index out of range

Any advice would be much appreciated!

**Comment by Patg13** [comment]
Hi

Could you post the text file and your group file ? I will check on my side what could cause this.
Could you also post the command you used to launch the program please ?

As to answer your question, the species tag list is a comma separated values of every of your species name that were used. The correct way to pass this information to the program is:
-c SPC1,SPC2,SPC3

If you specified a text file for the -c argument, it will not work

**Comment by Patg13** [comment]
Could you also post the command you used to launch the program please ?

**Comment by Patg13** [comment]
As to answer your question, the species tag list is a comma separated values of every of your species name that were used. The correct way to pass this information to the program is:
-c SPC1,SPC2,SPC3

If you specified a text file for the -c argument, it will not work.

**Comment by emgiles** [comment]
Hi 
Thank you so much for the quick reply. 
My sp text file looks like this:
Scurscur,Scurvird,Scurzebr,Lottgiga,Patevulg,Halirubr

My groups file looks like this:
Halirubr|HR_046546586.1	Halirufe|HU_048252459.1	Halirufe|HU_048252460.1	Halirufe|HU_048252461.1	patevulg|PA_050409076.2	Lottgiga|LGO97729.1	Scurscur|SS4891.t1	Scurviri|SV5844.t1	Scurzebr|SZ7807.t1	Scurviri|SV5843.t1	Scurscur|SS4892.t1

I am now seeing that one of my species is lowercase. I am going to change that in the species and regroup files and convert to csv. 
I am also now discovering that using an upset plot might be better than a Venn diagram if I want to look at so many species at once. The upset plot from R UpSetR was easy to make from the orthologous groups frequency table converted to binary.
THANKS!

**Comment by Patg13** [comment]
Does your group file contain the group number ? When I create this program, OrthoMCL group file had this format:
grp_4: PLUT|XP_011559157.1 PLUT|XP_011559158.1 PLUT|XP_011564859.1 PLUT|XP_011564860.1 PLUT|XP_011562320.1 PLUT|XP_011562647.1

**Comment by emgiles** [comment]
Hey Patrick,
So I have several different files. I have a file without group ID/number and I have a file with group ID. With your program I have been using the file without the group ID as you mentioned to use the raw output from OrthoMCL. Perhaps instead I should use the one with group ID?

**Comment by Patg13** [comment]
Yep, the file with the group id is the correct one. It was clearer in my head when I did the README... Sorry for that.

**Comment by emgiles** [comment]
Aha! Thanks for the info! I greatly appreciate your help and sharing of materials.

**Comment by Patg13** [comment]
Anytime ! Let me know if that work !

**Comment by Patg13** [comment]
> I am also now discovering that using an upset plot might be better than a Venn diagram if I want to look at so many species at once. The upset plot from R UpSetR was easy to make from the orthologous groups frequency table converted to binary. THANKS!

That's a very interesting way to display the results, I'll have to check if I could implement it for data with more than 6 species, thank you for the info !

**Comment by Patg13** [comment]
I'll close the issue, feel free to write again if the problem persist.
